Mappings: # Declare AMI for specific region
  RegionMap:
    ap-southeast-2:
      AMI: ami-06ce513624b435a22
    ap-southeast-1:
      AMI: ami-00b8d9cb8a7161e41
    us-east-1:
      AMI: ami-0be2609ba883822ec
    us-ease-2:
      AMI: ami-0a0ad6b70e61be944
    
  
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId:                     # Fetch Amazon Linux AMI from Mapping based on region
        !FindInMap
          - RegionMap
          - !Ref AWS::Region
          - AMI
      Tags:
        - Key: 'Name'
          Value: !Join
            - ""
            - - "Mapping AMI to Regions "
              - !Ref AWS::Region
      SecurityGroups:
        - !Ref MyNewSG
  MyNewSG:                          # Create new Security Group
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSh via port 22
      GroupName: MyNewSG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0





